server:
  port: 8080
  context-path: /myplan
spring:
  data:
    mongodb:
      database: myplan
      field-naming-strategy:
      host: localhost
      port: 27017
      repositories:
        enabled: true
